# Generated by Django 5.1.3 on 2024-11-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='post_files/')),
                ('code', models.IntegerField(default=0, unique=True, verbose_name='Код файла')),
                ('download_count', models.IntegerField(default=0, verbose_name='Скачиваний')),
            ],
            options={
                'verbose_name': 'Файл поста',
                'verbose_name_plural': 'Файлы постов',
            },
        ),
    ]
